version: "3.8"

services:
  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./front/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount custom Nginx configuration

